# Generated by Django 3.1 on 2020-08-24 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Razão social')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='Apelido')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=40, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=15, verbose_name='CEP')),
                ('state_registration', models.CharField(blank=True, max_length=30, verbose_name='inscrição estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=30, verbose_name='inscrição municipal')),
                ('logo', models.ImageField(blank=True, default='default-logo.png', null=True, upload_to='logos/%d/%m/%Y/', verbose_name='logo')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'clients',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
