# Generated by Django 3.1.5 on 2021-01-11 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Razão social')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='Apelido')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=40, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=15, verbose_name='CEP')),
                ('district', models.CharField(blank=True, max_length=30, verbose_name='Bairro')),
                ('address', models.CharField(blank=True, max_length=60, verbose_name='Endereço')),
                ('state_registration', models.CharField(blank=True, max_length=30, verbose_name='inscrição estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=30, verbose_name='inscrição municipal')),
                ('logo', models.ImageField(blank=True, default='default-logo.png', null=True, upload_to='logos/%d/%m/%Y/', verbose_name='logo')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mail', models.CharField(blank=True, max_length=120, null=True, verbose_name='E-Mail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='PasswordSafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('warning', 'alert-triangle'), ('complete', 'check-circle'), ('block-user', 'user-minus')], max_length=20, null=True)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente-Usuário',
                'verbose_name_plural': 'Cliente-Usuários',
            },
        ),
    ]
