# Generated by Django 3.1 on 2020-08-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200824_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, choices=[('warning', 'alert-triangle'), ('complete', 'check-circle'), ('block-user', 'user-minus')], max_length=20, null=True),
        ),
    ]
