# Generated by Django 3.1 on 2020-09-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_enterpriseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='host',
        ),
        migrations.RemoveField(
            model_name='locator',
            name='host',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Locator',
        ),
    ]
