# Generated by Django 3.1.4 on 2020-12-02 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0010_auto_20200914_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mail',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.client'),
        ),
        migrations.AlterField(
            model_name='passwordsafe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
