# Generated by Django 3.1.4 on 2020-12-02 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0011_auto_20201202_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='enterpriseuser',
            options={'verbose_name': 'Cliente-Usuário', 'verbose_name_plural': 'Cliente-Usuários'},
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/%d/%m/%Y/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='enterpriseuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
