# Generated by Django 3.1.4 on 2020-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201202_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, default='default-logo.png', null=True, upload_to='logos/%d/%m/%Y/', verbose_name='logo'),
        ),
    ]
