version: '3'

services:
  database:
    image: mysql:8.0
    container_name: portald-mysql
    networks:
      - us-east-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  portald:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portald
    networks:
      - us-east-1
    volumes:
      - ${PORTAL_HOME}:/usr/src/app
    ports:
      - "${PORTALD_PORT}:8000"
    tty: true
    command: [
      "/root/wait-for-mysql.sh",
      "${MYSQL_HOST}",
      "${MYSQL_USER}",
      "${MYSQL_PASSWORD}",
      "python3", "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]
    depends_on:
      - database

networks:
  us-east-1:
    driver: bridge

volumes:
  data_mysql:
  dbdata:
