version: '3'

services:
  portald:
    build: .
    container_name: portald
    network_mode: "host"
    volumes:
      - ${PORTAL_HOME}:/var/www/portald
    ports:
      - "${PORTALD_PORT}:8100"
      - "9000:80"
    tty: true
    command: ["/wait-for-mysql.sh", "${MYSQL_HOST}", "${MYSQL_ROOT_PASSWORD}", "/usr/bin/python3", "manage.py", "runserver", "0.0.0.0:8100", "--insecure"]