version: '3'

services:
  database:
    image: mysql
    container_name: portald-mysql
    networks:
      - us-east-2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  wcm:
    build: .
    container_name: portald
    networks:
      - us-east-2
    volumes:
      - ./portald/:/var/www/portald
    ports:
      - "8080:8080"
      - "8080:80"
    tty: true
    command: ["/wait-for-mysql.sh", "database-mysql", "${MYSQL_ROOT_PASSWORD}", "/usr/sbin/apache2ctl", "-DFOREGROUND"] ## , "/usr/bin/python3", "manage.py", "runserver", "0.0.0.0:8100"
    depends_on:
      - database

networks:
  us-east-1:
    driver: bridge

volumes:
  data_mysql:
  dbdata: