version: '3'

services:
  portald:
    build: .
    container_name: portald
    network_mode: "host"
    volumes:
      - ${PORTAL_HOME}:/var/www/portald
    tty: true
    command: ["/wait-for-mysql.sh", "${MYSQL_HOST}", "${MYSQL_ROOT_PASSWORD}", "/usr/bin/python3", "manage.py", "runserver", "0.0.0.0:${PORTALD_PORT}", "--insecure"]