version: '3'

services:
  portald:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portald
    ports:
      - ${PORTALD_PORT}:8000
    volumes:
      - ./portald:/usr/src/app
    tty: true
    command: [
      "python3", "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]