# ********************************************************
#                                                        #
# ███╗   ███╗███╗   ██╗ ██████╗      ██████╗██╗     ██╗  #
# ████╗ ████║████╗  ██║██╔════╝     ██╔════╝██║     ██║  #
# ██╔████╔██║██╔██╗ ██║██║  ███╗    ██║     ██║     ██║  #
# ██║╚██╔╝██║██║╚██╗██║██║   ██║    ██║     ██║     ██║  #
# ██║ ╚═╝ ██║██║ ╚████║╚██████╔╝    ╚██████╗███████╗██║  #
# ╚═╝     ╚═╝╚═╝  ╚═══╝ ╚═════╝      ╚═════╝╚══════╝╚═╝  #
#                                                        #
# ********************************************************
# ========================================================
# API configure
# ========================================================
api:
    ip: 'localhost'
    port: 8080
    credentials:
        user: 'api'
        passwd: 'api'
        base64auth: ''