# Generated by Django 3.1.7 on 2021-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cor'),
        ),
    ]
