# Generated by Django 3.1 on 2020-08-25 21:06

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.CharField(blank=True, default=time.time, max_length=30),
        ),
    ]
