# Generated by Django 3.1 on 2020-08-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200825_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='lido'),
        ),
    ]
