# Generated by Django 3.1 on 2020-09-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_application_host_inventory_locator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='physical_cores',
            new_name='cores',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='current_frequency',
            new_name='frequency',
        ),
    ]
