# Generated by Django 3.1 on 2020-08-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200827_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
