# Generated by Django 3.1 on 2020-09-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200908_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='current frequency'),
        ),
        migrations.AlterField(
            model_name='host',
            name='platform',
            field=models.CharField(max_length=100, verbose_name='platform'),
        ),
    ]
