# Generated by Django 3.1 on 2020-08-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message_read_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='username'),
        ),
    ]
