# Generated by Django 3.1 on 2020-09-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200908_1520'),
        ('api', '0005_auto_20200908_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Aplicações'},
        ),
        migrations.AddField(
            model_name='inventory',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.client'),
        ),
    ]
