# Generated by Django 3.1 on 2020-09-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200908_1520'),
        ('api', '0006_auto_20200914_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.client')),
            ],
            options={
                'verbose_name_plural': 'Inventário',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Hosts'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Anotações'},
        ),
        migrations.AddField(
            model_name='host',
            name='equipment',
            field=models.CharField(blank=True, choices=[('virtual', 'Virtual Machine'), ('real', 'Physical Machine'), ('docker', 'Container Docker')], max_length=30, null=True, verbose_name='equipamento'),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='hostinventory',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.host'),
        ),
    ]
