# Generated by Django 3.1 on 2020-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200827_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='commented by'),
        ),
    ]
