# Generated by Django 3.1 on 2020-09-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_inventory_enterprise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventários'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='host',
        ),
        migrations.RemoveField(
            model_name='locator',
            name='host',
        ),
        migrations.AddField(
            model_name='application',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='applications',
            field=models.ManyToManyField(to='api.Application'),
        ),
        migrations.AddField(
            model_name='host',
            name='locators',
            field=models.ManyToManyField(to='api.Locator'),
        ),
        migrations.DeleteModel(
            name='HostInventory',
        ),
    ]
