# Generated by Django 3.1 on 2020-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200914_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='private_ip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ip privado'),
        ),
        migrations.AddField(
            model_name='host',
            name='public_ip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ip público'),
        ),
    ]
