# Generated by Django 3.1 on 2020-09-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20200914_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='subject')),
                ('timestamp', models.CharField(blank=True, default=time.time, max_length=30)),
                ('msg', models.TextField(verbose_name='message')),
                ('read', models.BooleanField(blank=True, default=False, null=True, verbose_name='lido')),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('read_in', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Anotações',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(to='api.Comment'),
        ),
        migrations.AddField(
            model_name='note',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
