# Generated by Django 3.1 on 2020-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200914_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(to='api.Comment'),
        ),
    ]
