# Generated by Django 3.1 on 2020-09-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200914_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, to='api.Application'),
        ),
        migrations.AlterField(
            model_name='host',
            name='locators',
            field=models.ManyToManyField(blank=True, null=True, to='api.Locator'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hosts',
            field=models.ManyToManyField(blank=True, null=True, to='api.Host'),
        ),
    ]
