# Generated by Django 3.1 on 2020-09-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200914_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='host',
            name='locators',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='note',
            name='comments',
        ),
        migrations.AddField(
            model_name='application',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.host'),
        ),
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.note'),
        ),
        migrations.AddField(
            model_name='locator',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.host'),
        ),
    ]
