# Generated by Django 3.1 on 2020-09-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200908_1520'),
        ('api', '0017_auto_20200914_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.client'),
        ),
    ]
