# Generated by Django 3.1 on 2020-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200915_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ip',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
