# Generated by Django 3.1 on 2020-09-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200915_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name_plural': 'Instâncias'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='environment',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inventory'),
        ),
    ]
