# Generated by Django 3.1 on 2020-09-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200915_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='hostname',
            new_name='database',
        ),
    ]
