# Generated by Django 3.1 on 2020-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200923_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='database',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
