# Generated by Django 3.1 on 2020-10-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201008_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
    ]
