# Generated by Django 3.1 on 2020-11-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_host_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service'),
        ),
    ]
