# Generated by Django 3.1 on 2020-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='database',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
