# Generated by Django 3.1.5 on 2021-01-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201202_1627'),
        ('api', '0026_auto_20201110_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.client'),
        ),
    ]
