# Generated by Django 3.1.5 on 2021-01-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
                ('subcaption', models.CharField(blank=True, max_length=50, null=True)),
                ('yAxis_plot_value', models.CharField(blank=True, max_length=30, null=True)),
                ('yAxis_plot_type', models.CharField(blank=True, max_length=30, null=True)),
                ('yAxis_title', models.CharField(max_length=40)),
                ('yAxis_format_prefix', models.CharField(blank=True, max_length=40, null=True)),
                ('schema', models.TextField(blank=True, null=True)),
                ('from_zabbix', models.BooleanField(default=False, null=True)),
                ('number_data', models.IntegerField(blank=True, default=100, null=True)),
                ('itemid', models.CharField(blank=True, max_length=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.client')),
            ],
            options={
                'verbose_name': 'Gráfico',
                'verbose_name_plural': 'Gráficos',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('value', models.TextField()),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.chart')),
            ],
        ),
    ]
