# Generated by Django 3.1 on 2020-09-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=14)),
                ('caption_text', models.CharField(blank=True, max_length=50, null=True)),
                ('yAxis_plot_value', models.CharField(blank=True, max_length=30, null=True)),
                ('yAxis_plot_type', models.CharField(blank=True, max_length=30, null=True)),
                ('yAxis_title', models.CharField(max_length=40)),
                ('yAxis_format_prefix', models.CharField(blank=True, max_length=40, null=True)),
                ('schema', models.CharField(max_length=255)),
                ('columns', models.CharField(blank=True, default='col-md-6', max_length=20, null=True)),
            ],
        ),
    ]
