# Generated by Django 3.1 on 2020-09-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='max_height',
            field=models.IntegerField(blank=True, default=450),
        ),
        migrations.AddField(
            model_name='chart',
            name='max_width',
            field=models.IntegerField(default=700, null=True),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('value', models.CharField(max_length=30)),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charts.chart')),
            ],
        ),
    ]
