# Generated by Django 3.1 on 2020-09-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20200930_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
