# Generated by Django 3.1 on 2020-10-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20200914_1806'),
        ('charts', '0003_auto_20200930_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.client'),
        ),
    ]
