# Generated by Django 3.1 on 2020-10-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_chart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.TextField(),
        ),
    ]
