# Generated by Django 3.1 on 2020-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20201002_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='uid',
            field=models.CharField(max_length=20),
        ),
    ]
