# Generated by Django 3.1 on 2020-10-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_auto_20201008_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='caption_text',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='max_height',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='max_width',
        ),
        migrations.AddField(
            model_name='chart',
            name='subcaption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
