# Generated by Django 3.1 on 2020-11-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_auto_20201029_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='from_zabbix',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
