# Generated by Django 3.1 on 2020-11-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_chart_number_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='itemid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
