# Generated by Django 3.1.4 on 2020-12-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0010_chart_itemid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'verbose_name': 'Gráfico', 'verbose_name_plural': 'Gráficos'},
        ),
    ]
